# Generated by Django 4.0.2 on 2022-02-03 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('grateful_for1', models.TextField(default='')),
                ('grateful_for2', models.TextField(default='')),
                ('grateful_for3', models.TextField(default='')),
                ('thoughts', models.TextField(default='')),
                ('daily_pic', models.ImageField(default='nice_pic.jpg', upload_to='daily_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
